### Logistic Regression

- sklearn: Regularization by default
- statsmodels: you choose

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()
X, y = cancer.data, cancer.target

In [3]:
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.preprocessing import StandardScaler

In [4]:
from sklearn.pipeline import make_pipeline

In [5]:
pipe = make_pipeline(StandardScaler(), LogisticRegression())

In [6]:
pipe.fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [7]:
pipe.score(X, y)

0.9876977152899824

In [8]:
pipe.named_steps['logisticregression'].coef_

array([[-0.36317072, -0.38770299, -0.35111444, -0.43555896, -0.16176493,
         0.56259548, -0.85989759, -0.96222175,  0.07616775,  0.32218585,
        -1.29103479,  0.26892526, -0.65988685, -1.01250087, -0.27717046,
         0.7362824 ,  0.11052647, -0.3335099 ,  0.29590225,  0.68091528,
        -1.02936114, -1.31459312, -0.82331706, -1.01059356, -0.67073135,
         0.04465888, -0.87330064, -0.91195815, -0.88789694, -0.47983137]])

In [9]:
coefs = pipe.named_steps['logisticregression'].coef_

In [10]:
pipe.named_steps['standardscaler'].inverse_transform(coefs)

array([[ 1.28485855e+01,  1.76235900e+01,  8.34448107e+01,
         5.01744502e+02,  9.40871985e-02,  1.34027083e-01,
         2.03087092e-02,  1.16150282e-02,  1.83248111e-01,
         6.50703591e-02,  4.74664130e-02,  1.36507520e+00,
         1.53303691e+00, -5.68211174e+00,  6.20950124e-03,
         3.86520245e-02,  3.52271419e-02,  9.74009501e-03,
         2.29861863e-02,  5.59507006e-03,  1.12984125e+01,
         1.76044984e+01,  7.96199876e+01,  3.05700456e+02,
         1.17067631e-01,  2.61285338e-01,  9.01569343e-02,
         5.47137777e-02,  2.35191928e-01,  7.52870733e-02]])

In [11]:
from statsmodels.discrete.discrete_model import Logit

In [14]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [15]:
ss = StandardScaler()
xs = ss.fit_transform(X)

In [16]:
logit = Logit(y, xs).fit()

Optimization terminated successfully.
         Current function value: 0.023921
         Iterations 19


/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1747: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))


In [17]:
print(logit.summary())

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                  569
Model:                          Logit   Df Residuals:                      539
Method:                           MLE   Df Model:                           29
Date:                Tue, 05 Jan 2021   Pseudo R-squ.:                  0.9638
Time:                        20:05:24   Log-Likelihood:                -13.611
converged:                       True   LL-Null:                       -375.72
Covariance Type:            nonrobust   LLR p-value:                8.618e-134
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1           287.0824    202.609      1.417      0.157    -110.023     684.188
x2            -1.9736      3.615     -0.546      0.585      -9.058       5.111
x3          -155.1279    128.148     -1.211      0.2

/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1747: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))


In [18]:
logit2 = Logit(y, X).fit_regularized()

/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1747: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1800: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


Optimization terminated successfully.    (Exit mode 0)
            Current function value: 9.896888543646089e-11
            Iterations: 564
            Function evaluations: 585
            Gradient evaluations: 564


In [19]:
print(logit2.summary())

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                  569
Model:                          Logit   Df Residuals:                      539
Method:                           MLE   Df Model:                           29
Date:                Tue, 05 Jan 2021   Pseudo R-squ.:                   1.000
Time:                        20:06:24   Log-Likelihood:            -5.6313e-08
converged:                       True   LL-Null:                       -375.72
Covariance Type:            nonrobust   LLR p-value:                1.737e-139
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1          1.018e+04   9.49e+09   1.07e-06      1.000   -1.86e+10    1.86e+10
x2          -109.5802   3.83e+09  -2.86e-08      1.000    -7.5e+09     7.5e+09
x3           554.7912        nan        nan        n

/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:1354: RuntimeWarning: invalid value encountered in sqrt
  bse_ = np.sqrt(np.diag(self.cov_params()))
/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:1747: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))


In [20]:
no_reg_sklearn = LogisticRegression(C = 10_000)

In [21]:
no_reg_sklearn.fit(X, y)

/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=10000)

In [22]:
lrcv = LogisticRegressionCV()

In [23]:
lrcv.fit(xs, y)

/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/

LogisticRegressionCV()

In [24]:
lrcv.fit(xs, y)

/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/

LogisticRegressionCV()

In [25]:
lrcv.Cs_

array([1.00000000e-04, 7.74263683e-04, 5.99484250e-03, 4.64158883e-02,
       3.59381366e-01, 2.78255940e+00, 2.15443469e+01, 1.66810054e+02,
       1.29154967e+03, 1.00000000e+04])

In [26]:
lrcv.C_

array([0.35938137])

In [27]:
lrcv.score(xs, y)

0.9876977152899824

In [28]:
xs[0]

array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
        3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
        2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
        1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
        1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
        2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])

In [32]:
lrcv.predict_log_proba(xs[0].reshape(1, 30))

array([[-1.33219726e-07, -1.58312661e+01]])

In [33]:
lrcv.predict_proba(xs[0].reshape(1, 30))

array([[9.99999867e-01, 1.33219717e-07]])

In [34]:
lrcv.predict(xs[0].reshape(1, 30))

array([0])